<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Theme Manifest Path
    |--------------------------------------------------------------------------
    |
    | Path to the themes manifest JSON file generated by the Vite plugin.
    | This file contains theme metadata including colors and preview data.
    |
    */

    'manifest_path' => public_path('tardis-assets/themes-manifest.json'),

];
